# Uses git diff to list changed files, outputs the filenames by language
# outputs.js - .js/.jsx files
# outputs.ts - .ts/.tsx
# outputs.ex - .ex/.exs/.eex
# outputs.scss - .scss
#
# This works for our needs, but if our use case intensifies maybe using 
# https://github.com/marketplace/actions/changed-files will help

name: List changed files
on: 
  workflow_call:
    inputs:
      # If set to true, then everything will be listed as "changed"
      force:
        required: false
        type: boolean
        default: false

    outputs:
      js: 
        description: "JavaScript files changed"
        value: ${{ jobs.files.outputs.js }}
      ts: 
        description: "TypeScript files changed"
        value: ${{ jobs.files.outputs.ts }}
      ex: 
        description: "Elixir files changed"
        value: ${{ jobs.files.outputs.ex }}
      scss: 
        description: "CSS files changed"
        value: ${{ jobs.files.outputs.scss }}
      any:
        description: "Any JS, TS, Elixir, or CSS file changes?"
        value: ${{ jobs.files.outputs.js || jobs.files.outputs.ts || jobs.files.outputs.ex || jobs.files.outputs.scss }}

jobs:
  files:
    name: List changed files
    runs-on: ubuntu-20.04
    outputs:
      js: ${{ steps.changes.outputs.js }}
      ts: ${{ steps.changes.outputs.ts }}
      ex: ${{ steps.changes.outputs.ex }}
      scss: ${{ steps.changes.outputs.scss }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: changes
        name: Compute changed files
        shell: bash
        run: |
          if [[ ${{ inputs.force }} == 'true' ]]; then
            echo "js=true" >> $GITHUB_OUTPUT
            echo "ts=true" >> $GITHUB_OUTPUT
            echo "scss=true" >> $GITHUB_OUTPUT
            echo "ex=true" >> $GITHUB_OUTPUT
          else
            changes () { git diff --name-only --diff-filter=ACDMRT ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} ; }
            echo "js=$(changes | grep -E 'assets/js/.*\.jsx?' | xargs)" >> $GITHUB_OUTPUT
            echo "ts=$(changes | grep -E 'assets/ts/.*\.tsx?' | xargs)" >> $GITHUB_OUTPUT
            echo "scss=$(changes | grep -E 'assets/css/.*\.scss' | xargs)" >> $GITHUB_OUTPUT
            echo "ex=$(changes | grep -E '.*(\.exs?|\.eex)' | xargs)" >> $GITHUB_OUTPUT
          fi
      - name: "List changed files:"
        run: echo "${{ toJSON(steps.changes.outputs) }}"
        shell: bash
