name: Elixir CI

on: [push]

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      id: elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: '1.10.3' # Define the elixir version [required]
        otp-version: '22.3.3' # Define the OTP version [required]
    - name: Restore dependencies cache
      id: deps-cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Check formatting
      run: mix format --check-formatted
    - name: Credo
      run: bash semaphore/credo.sh
    - name: Run tests
      run: env MIX_ENV=test mix do compile --force --warnings-as-errors, coveralls.json && bash <(curl -s https://codecov.io/bash)
    - name: Restore Dialyzer cache
      id: dialyzer-cache
      uses: actions/cache@v2
      with:
        path: _build/dev/dialyxir*.plt*
        key: ${{ runner.os }}-dialyxir-${{ steps.elixir.otp-version }}-${{ steps.elixir.elixir_version }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          ${{ runner.os }}-dialyxir-${{ steps.elixir.otp-version }}-${{ steps.elixir.elixir_version }}-
          ${{ runner.os }}-dialyxir-${{ steps.elixir.otp-version }}-
    - name: Dialyzer
      run: mix dialyzer --halt-exit-status
